name: Convert YAML to JSON

on:
  push:
    branches:
      - main
      - 'refs/pull/*'
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run YAML to JSON conversion script
        run: python convertor_to_json.py

      - name: Upload JSON as artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-json
          path: resume.json
