name: Проверка пулл реквестов

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка зависимостей
        run: |
          # Установите yamllint
          sudo apt-get install -y yamllint

      - name: Проверка синтаксиса YAML
        run: |
          # Проверьте все YAML файлы в репозитории
          yamllint .
  
